### ISSUE TITLE
[REFACTOR] DetailMapVC 기능 정리

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#103]
## 📌  Feature Issue
상속 및 재사용을 위한 DetailMapVC 기능 정리
- 기존 나의 운동 기록 데이터만 확인하던 DetailMapVC를 메서드 기능별로 정리하여
운동기록 확인과 챌린지 기록 확인에서 상속받아 사용할 수 있도록 정리

## 📝  To-do

- [ ] 메서드 주석 추가
- [ ] configure 메서드 정리
- [ ] draw 메서드 기능 정리
