### ISSUE TITLE
[REFACTOR] 홈화면 영역 추가 비용 줄이기

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#116]
## 📌  Feature Issue
홈화면 영역 추가 비용 줄이기

## 📝  To-do

- [ ] 현재 보이는 지도의 영역만 받아오도록 홈화면 조회 api 수정
- [ ] 새로고침 시 removeAll & add 구조에서 추가 안된 영역만 add하도록 변경
- [ ] 기록 시작 api 홈과 통일
