### ISSUE TITLE
[FIX] 서버 response 값 변경 수정반영

### ISSUE THREAD

**Issue by iowa329** [dnd-side-project/dnd-7th-1-iOS#117]
## 📌  Feature Issue
서버 코드 수정으로 인한 Response 값 변경 및 관련된 Model 파일 수정 반영

## 📝  To-do
- [x] 챌린지 생성 Req, res
- [x] 챌린지 생성 완료 Res
- [x] 진행 대기 중 챌린지 목록 조회 Res
- [x] 진행 중 챌린지 목록 조회 Res
- [x] 친구와 함께 진행 중인 챌린지 목록 조회 Res
- [x] 진행 완료된 챌린지 목록 조회 Res
- [x] 진행 대기 중 챌린지 상세 조회 Res
- [x] 진행 중 챌린지 상세 조회 Res
- [x] 챌린지 색깔 타입 Green 추가
- [x] 챌린지 색깔 Res Upper-case로 변경
- [x] 걸음수 랭킹 API 주소 변경(-> /matrix/rank/step) 및 요청 유형 변경(POST -> GET)
- [x] 챌린지 랭킹 조회 파라미터 start, end -> started, ended로 변경 (전체 통일)
- [x] 영역수 랭킹(/matrix/rank/widen) 요청 유형 변경(POST -> GET)
- [x] 챌린지 상세지도(challenge/detail/map) 파라미터 값 변경(nickname 추가) 수정반영
- [x] 변경된 챌린지 상세정보 기간(start, end) Res 값 대응
