### ISSUE TITLE
[FEAT] 푸시알림 화면전환 서버연동

### ISSUE THREAD

**Issue by iowa329** [dnd-side-project/dnd-7th-1-iOS#132]
## 📌  Feature Issue
푸시알림 클릭시 해당 알림에 맞는 화면전환 이동 코드 서버연동 테스트 작업

## 📝  To-do
- [x] 친구 요청 화면전환
- [ ] 친구 승낙 화면전환
- [ ] 챌린지 초대 화면전환
- [ ] 챌린지 수락 화면전환
- [ ] 챌린지 진행 화면전환
- [ ] 챌린지 취소 화면전환
- [ ] 챌린지 결과 화면전환
