### ISSUE TITLE
[FEAT] 지도 Gesture와 영역 새로고침 연결

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#143]
## 📌  Feature Issue
보다 나은 사용성을 위해 기존 새로고침으로만 진행되던 영역 받아오기를 드래그에 연결

## 📝  To-do

- [x] gesture 시작 시 기존 isFocus 값을 false로 변경하는 메서드 삭제
- [x] 드래그 1초 후 영역 통신 시작 -> 제스쳐 연타를 막기위함
- [x] 통신 코드 연결 /matrix
   - [x] 첫 통신에서 모두 받아오는 친구와 나의 목록을 가져다가 닉네임: 색상 딕셔너리를 만들고
   - [x] /matrix로 받아온 닉네임과 영역 좌표만을 받아 테이블에서 색상을 받아서 영역 추가
