### ISSUE TITLE
[ADD] 친구 프로필 친구추가 API 연결, 오류 수정

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#149]
## 📌  Feature Issue

친구 프로필 기능 추가 및 수정

## 📝  To-do

- [x] 디코딩 에러 해결
- [x] 친구 추가 API 연결
- [x] 토스트 메세지 추가
- [x] viewWillAppear, viewWillDisappear 경고 수정
