### ISSUE TITLE
[BUG] 테플 전, 자잘한 수정

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#166]
### 📝 todo
- [x] 온보딩 pageControl 오류 수정
- [x] 키보드 완료 키 기능 추가
- [x] 위치 동의 화면 이미지 비율 조정
- [x] 마이페이지 캘린더 - 운동 기록 목록 tableView '데이터가 없습니다' 데이터 개수에 맞게 연결
- [x] 회원가입에 로딩뷰 넣기
- [x] (임시) 다크모드 막기
- [x] 홈화면 진행중인 챌린지 목록 높이 동적으로 변경
   - [x] 레이아웃 경고 수정
   - [x] 진행중인 챌린지로 이동
   - [x] 챌린지 생성 화면으로 이동
- [x] 친구 프로필 챌린지 연결
- [x] 운동 기록 상세 챌린지 연결
- [x] 활동 상세 기록 수정 화면 알림창 연결 & 제스쳐 뒤로가기 막기 & 완료 시 토스트 메세지 연결
- [x] 헬스 데이터 접근 동의 지도에서 받도록 변경
- [x] 온보딩 이미지 AutoLayout 적용 -> 비율
- [x] 세로모드만 허용
- [x] tableView 높이가 동일하고 바뀔 일 없는 경우 tableView delegate - heightForRowAt를 rowHeight로 변경
- [x] 운동 기록 전송 -> 로딩 넣기
