### ISSUE TITLE
[FEAT] API 에러 처리

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#167]
## 📌  Feature Issue
에러 처리 및 알림창 연결

## 📝  To-do

- [x] ErrorResponseModel 생성 및 적용
- [x] ErrorHandlingProtocol 구현 및 BaseViewController에서 상속
- [x] apiError 연결 -> 에러 알람창 연결(에러 코드에 맞는 타이틀, 메세지, 코드 연결)
