### ISSUE TITLE
[FEAT] 마이페이지 친구 목록 레이아웃 변경 및 API 연결

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#171]
## 📌  Feature Issue
마이페이지 친구 목록 레이아웃 변경 및 API 연결

## 📝  To-do

- [x] 친구 목록 레이아웃 변경 (친구 요청 max 3개에서 스크롤)
- [x] 친구 신청 / 삭제 연결
- [x] 친구 목록 편집 구현
- [x] 친구 삭제 알림창 연결
- [x] 친구 목록 API 연결
- [x] 토스트메세지 연결

검색 이슈에서 처리
- [ ] 검색시 키보드 상승에 따른 화면 스크롤 -> baseScrollView 추가하기
- [ ] 친구 검색 기능 구현
