### ISSUE TITLE
[CHORE] 회원가입 화면 순서 변경 및 추가/삭제

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#172]
## 📌  Feature Issue
회원가입 화면 순서 변경 및 추가/삭제
+) #174 

## 📝  To-do

- [x] 추천 친구 동의 화면 구현
- [x] 회원가입 화면 순서 변경
- [ ] 애플 로그인 / 카카오 로그인에 따라 친구 목록 분기 처리
- [x] EnterVC 삭제
