### ISSUE TITLE
[FEAT] 회원가입 요청 파라미터 변경

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#174]
## 📌  Feature Issue
- 회원가입 전, 친구추가를 진행하던 프로세스에서 친추를 보낼 친구를 선택하는 방법으로 로직이 변경됨에 따라
친구 목록에서 선택한 친구들을 배열로 만들어 최종 회원가입에서 친구 목록 전달
- 추천 친구 목록에 나타날 것인지 동의 받는 화면 구현
- 추천 친구 목록에 나타날 것인지 지정하는 isExceptRecommend 값 추가

## 📝  To-do

- [ ] 카카오 친구 목록 api 연결
- [ ] 친구 추가 버튼 연결 -> 친구 목록 생성
- [ ] 추천 친구 동의 화면 구현
- [ ] 추천 친구 동의 상태 연결

**Comment by yunkyung-Hwang** [comment]
#172 랑 합침
