### ISSUE TITLE
[FIX] 챌린지 관련 기능 점검

### ISSUE THREAD

**Issue by iowa329** [dnd-side-project/dnd-7th-1-iOS#179]
## 📌  Feature Issue
챌린지와 관련된 기능 코드 점검

## 📝  To-do
- [x] 챌린지 목록(진행 대기중, 진행 중, 진행완료) 셀 재사용 문제점 점검
- [x] ~~진행 혹은 완료 챌린지 상세페이지 - 상세지도의 참가자 목록 레이아웃 어긋남 문제 수정~~
- [x] 챌린지 생성 버튼바인딩 내부 NavigationController 호출 방식 변경(rootViewController -> self) 및 guard let self 구문 추가
- [x] 챌린지 목록 새로고침 방식 변경(메뉴바 항목 클릭 -> 전 챌린지 목록 viewWillApear 시점에서 호출)
- [x] 챌린지 관련 테이블뷰 (고정된) height 관련 델리게이트 호출 코드 제거
- [x] ~~챌린지 진행중, 진행완료 서버 코드 파라미터 값 점검~~
- [x] 진행 중인 챌린지 상세페이지 d-day 표시 오류 수정(ex. 14일날 14일까지 진행하는 챌린지 조회 시 0으로 표기되는 문제)
- [x] 챌린지 생성 - 친구 목록 불러오는 서버 코드 리스펀스 값 수정
