### ISSUE TITLE
[ADD] 챌린지 상세지도 구조 변경 및 기능 추가

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#182]
## 📌  Feature Issue
챌린지 상세지도 랭킹 목록 구조 변경 및 기능 추가
영역 API 파라미터(SpanDelta) 추가
제스쳐 바인딩

## 📝  To-do

- [x] 첫 통신 spanDelta 파라미터 추가
- [x] 제스쳐 바인딩
- [x] 제스쳐 막힌거 수정
- [x] 랭킹 목록 tableView로 변경
- [x] 랭킹 tableView select event 추가(해당 유저 위치(마커)로 이동)
