### ISSUE TITLE
[CHORE] 자잘한 수정

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#216]
## 📝  To-do

- [x] LoginVC -> ViewWillAppear nickname 지우기
- [x] 친구 anntation isUserInteractionEnabled 확인
- [x] 친구 추천 목록 제외 반대로 되어있는거 수정
