### ISSUE TITLE
[FEAT] 알림함 목록 동적 리스펀스 값 처리

### ISSUE THREAD

**Issue by iowa329** [dnd-side-project/dnd-7th-1-iOS#221]
## 📌  Feature Issue
알림함 목록 각 항목 리스펀스 값의 data 파라미터 내부에 있는 값에 따라 적절한 액션을 주기 위한 동적 리스펀스 값(챌린지 알림의 경우 challenge uuid를, 그 외에는 빈 값을)에 대한 디코드 파싱 처리 작업

## 📝  To-do
- [x] 알림함 목록 동적 리스펀스 값 처리
- [x] 알림 종류별 각 화면 전환 작업 확인(uuid 있는 경우 챌린지 상세페이지로 전환, 친구초대는 친추화면으로 전환 등)
- [x] 알림함 비우기 버튼 클릭시 확인 알림창 추가(ex. 알림함을 비우시겠습니까?)
