### ISSUE TITLE
[FIX] 누적 랭킹 목록 조회 API 수정

### ISSUE THREAD

**Issue by iowa329** [dnd-side-project/dnd-7th-1-iOS#222]
## 📌  Feature Issue
변경된 누적 랭킹 조회 API(자신 랭킹 API + 페이징 누적 랭킹목록 API로 분리) 수정 반영

## 📝  To-do
- [x] 자신 누적 랭킹 조회 API 추가
- [x] 누적 랭킹 조회 페이징 구조 추가
- [x] 최초 회원가입 후 누적랭킹 목록 없는 문제 대응(0 혹은 - 표시 필요)
