### ISSUE TITLE
[FEAT] 기록 완료 화면 서버 연결 및 UI

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#26]
## 📌  Feature Issue

기록 완료 화면 서버 연결 및 UI

## 📝  To-do

- [x] 운동 기록 + 상세 메모 post
- [x] miniMap span 수정
- [x] miniMap 좌표 오류 수정
- [x] 상세 지도 화면 구현
