### ISSUE TITLE
[FEAT] 디자인 수정사항 반영

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#44]
## 📌  Feature Issue
디자인 수정사항 반영

## 📝  To-do

- [x] 영역 정사각형 만들기 (세로 길이 줄이기)
- [x] user Location custom
- [x] 거리 m -> km
- [x] insertComma
- [x] 카운트다운 화면 팁 추가
- [x] Asset: systemImage(chevron) -> arrow
