### ISSUE TITLE
[FEAT] 초기 사용자 정보 설정 화면 구현

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#51]
## 📌  Feature Issue
초기 사용자 정보 설정 화면 구현

## 📝  To-do

- [x] 닉네임 입력 화면 구현
- [x] 친구 추가 화면 구현
- [x] 시작 화면 구현
