### ISSUE TITLE
[ADD] 통신 모델 추가 및 변경

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#75]
## 📌  Feature Issue
서버 업데이트에 따른 isPublicRecord,  picturePath 추가
홈화면 친구 상태를 나타내는 isFriend 타입 변경 Bool -> String

## 📝  To-do

- [x] 회원가입: isPublicRecord추가
- [x] 프로필 조회: isFriend 변경, picturePath 추가
- [x] 운동 기록 정보: rank -> uuid
- [x] 나의 활동 기록 조회: total값 삭제
- [x] 회원 정보 조회(마이페이지): picturePath 추가
- [x] 홈화면: picturePath 추가 (3개)
- [x] 기록이 있는 날짜 조회: url 변경 (eventList -> event-list)
- [x] 기록 시작 //홈화면 모델과 동일
