### ISSUE TITLE
[FEAT] 친구 목록 화면 구현

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#76]
## 📌  Feature Issue
친구 목록 화면 구현

## 📝  To-do

- [x] 베이스 화면 구현
- [x] 친구 목록 화면 구현
- [x] 추천 친구 화면 구현
