### ISSUE TITLE
[FEAT] 랭킹목록 서버 재연결

### ISSUE THREAD

**Issue by iowa329** [dnd-side-project/dnd-7th-1-iOS#79]
## 📌  Feature Issue
랭킹목록 서버 재연결

## 📝  To-do
- [x] 영역 랭킹 서버연결
- [x] 걸음수 랭킹 서버연결
- [x] 역대 누적 랭킹 서버연결
