### ISSUE TITLE
[FEAT] 기록 중 UI 구현 및 기능 테스트

### ISSUE THREAD

**Issue by yunkyung-Hwang** [dnd-side-project/dnd-7th-1-iOS#8]
## 📌  Feature Issue
기록 중 UI 구현 및 기능 테스트 진행
이동 거리 (아이폰 / 워치 건강 데이터  or 자체 계산) 구현 테스트

## 📝  To-do

- [x] 기록 중 화면 UI 구현
- [ ] 아이폰 건강데이터 받아오기
- [ ] 워치 건강데이터 받아오기
- [x] 칸 수 / 이동 거리 / 기록 시간 측정
