### ISSUE TITLE
[FIX] 챌린지/랭킹 탭 버그 수정

### ISSUE THREAD

**Issue by iowa329** [dnd-side-project/dnd-7th-1-iOS#95]
## 📌  Feature Issue
챌린지/랭킹 탭 내부의 버그들을 수정

## 📝  To-do
- [x] 랭킹 숫자에 표시되는 콤마 함수 표기 오류 문제
- [x] 챌린지 생성 과정에서 친구 추가 후 수정 할 때 레이아웃이 어긋나는 문제
- [x] 진행 대기중인 챌린지 목록에서 D-day 미표기 문제
- [x] 랭킹 프로필 이미지 셀 재사용시 문제 유무 파악
