### ISSUE TITLE
[FEAT] 챌린지 상세정보 페이지

### ISSUE THREAD

**Issue by iowa329** [dnd-side-project/dnd-7th-1-iOS#96]
## 📌  Feature Issue
챌린지 진행/대기 완료에 대한 상세정보 페이지 화면구성

## 📝  To-do
- [x] 챌린지 진행중 상세정보
- [x] 챌린지 진행완료 상세정보
- [x] 지도 상세 뷰 연결
